name: Build and Push docker images

on:
  release:
    types: [published]
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/social-credit-bot:latest
            ghcr.io/${{ github.repository_owner }}/social-credit-bot:${{ github.event.release.tag_name }}
